"""Beacons link-in-bio artifact generator.

Produces two output files per week (written to DATA_DIR/shop/artifacts/):

  beacons_weekly_pack_<week_of>.md
      Copy/paste-ready Beacons update pack:
      headline, disclosure, ordered links, CTA strategy, live promo blurb,
      and (if a live session is planned) the full run-of-show.

  weekly_offer_slate_<week_of>.json
      Machine-readable offer slate:
      week_of, offers array, cta_strategy, disclosure, live_run_of_show.

No paid Beacons API is required — the output is designed to be copy/pasted
into the free Beacons dashboard manually.
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from .models import ShopOffer, WeeklySlate
from ..config import SHOP_DIR, load_config

ARTIFACTS_DIR = SHOP_DIR / "artifacts"

# ── Compliance disclosure templates ───────────────────────────────────
#
# These templates satisfy FTC and TikTok creator disclosure requirements.
# Always display disclosure at the top of your Beacons page, in captions,
# and as a pinned comment on affiliate posts.
#
DISCLOSURE_TEMPLATES = {
    "short": "#ad — affiliate link, I earn a small commission.",
    "medium": (
        "Some links on this page are affiliate links. "
        "I earn a small commission if you purchase — at no extra cost to you. #ad"
    ),
    "full": (
        "Disclosure: This page contains affiliate links to products I recommend. "
        "As a TikTok Shop affiliate I may earn a commission on qualifying purchases "
        "at no additional cost to you. I only promote products I have reviewed or "
        "believe in. #ad #affiliate"
    ),
}


def generate_beacons_pack(slate: WeeklySlate, offers: list[ShopOffer]) -> str:
    """Render the Beacons weekly update pack as a Markdown string.

    The returned string is ready to be copy/pasted into the Beacons dashboard
    (title, description, link order, and promo blurb sections).
    """
    cfg = load_config()
    beacons_url = cfg.get("beacons_url", "https://beacons.ai/yourhandle")

    offer_map = {o.offer_id: o for o in offers}

    cta_note = (
        "✅ **CTA:** Tap the **product anchor** below each video (native TikTok Shop link)"
        if slate.cta_strategy == "tap_product_anchor"
        else f"✅ **CTA:** Direct viewers to your Beacons page → {beacons_url}"
    )

    lines: list[str] = [
        "# 🛍️ Beacons Weekly Update Pack",
        f"**Week of:** {slate.week_of}",
        "",
        "## 📣 Headline",
        slate.headline or "This Week's Top Picks",
        "",
        "## 📋 Disclosure",
        slate.disclosure,
        "",
        "## 🔗 Links (paste in this order into Beacons)",
    ]

    for i, oid in enumerate(slate.offer_ids, 1):
        offer = offer_map.get(oid)
        if not offer:
            continue
        price = f"${offer.price_usd:.2f}" if offer.price_usd else "see link"
        lines.append(f"{i}. **{offer.title}** — {price}")
        lines.append(f"   🔗 {offer.tiktok_product_url}")
        lines.append("")

    lines += [
        "## 🎯 CTA Strategy",
        cta_note,
        "",
        "## 💬 Live / Bio Promo Blurb",
        f"🛒 Shop my top picks this week → {beacons_url}",
        f"_{slate.disclosure}_",
        "",
    ]

    if slate.live_run_of_show:
        ros = slate.live_run_of_show
        lines += [
            "## 🎥 Live Shopping Run-of-Show",
            f"**Live title:** {ros.get('live_title', 'Weekly Shop Live')}",
            "",
            f"**Pinned comment:** {ros.get('pinned_comment', '')}",
            "",
            "**Minute-by-minute:**",
        ]
        for segment in ros.get("segments", []):
            lines.append(f"- {segment}")
        lines.append("")
        lines.append("**FAQ / Moderation snippets:**")
        for faq in ros.get("faq_snippets", []):
            lines.append(f"- {faq}")
        lines.append("")

    lines += [
        "---",
        f"*Generated by TikTok AI Swarm on {date.today().isoformat()}*",
        "",
        "> **Manual step:** copy the links above into your Beacons dashboard, "
        "update the headline and disclosure, then save. No API needed.",
    ]

    return "\n".join(lines)


def write_artifacts(
    slate: WeeklySlate, offers: list[ShopOffer]
) -> tuple[Path, Path]:
    """Write both artifact files and return (md_path, json_path).

    Files are written to ARTIFACTS_DIR (DATA_DIR/shop/artifacts/).
    """
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

    # ── Markdown pack ──────────────────────────────────────────────────
    md_content = generate_beacons_pack(slate, offers)
    md_path = ARTIFACTS_DIR / f"beacons_weekly_pack_{slate.week_of}.md"
    md_path.write_text(md_content, encoding="utf-8")

    # ── Machine-readable JSON slate ────────────────────────────────────
    offer_map = {o.offer_id: o for o in offers}
    slate_doc = {
        "week_of": slate.week_of,
        "offers": [
            offer_map[oid].to_dict()
            for oid in slate.offer_ids
            if oid in offer_map
        ],
        "cta_strategy": slate.cta_strategy,
        "disclosure": slate.disclosure,
        "headline": slate.headline,
        "live_run_of_show": slate.live_run_of_show,
        "created_at": slate.created_at,
    }
    json_path = ARTIFACTS_DIR / f"weekly_offer_slate_{slate.week_of}.json"
    json_path.write_text(json.dumps(slate_doc, indent=2), encoding="utf-8")

    return md_path, json_path
